name: Trigger CRON to update data

on:
    workflow_dispatch:
    schedule:
        - cron: "*/12 * * * *"
jobs:
    build:
        name: Trigger CRON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: scripts/cron.sh
